name: kiss_pocketbase_auth
description: PocketBase authentication provider for the kiss_auth package
version: 0.1.0
repository: https://github.com/WAMF/kiss_pocketbase_auth

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  kiss_auth: ^0.1.0
  pocketbase: ^0.23.0
  http: ^1.1.0

dev_dependencies:
  test: ^1.24.0
  lints: ^3.0.0
  process_run: ^0.14.2
  very_good_analysis: ^9.0.0

topics:
  - authentication
  - pocketbase
  - auth
  - jwt
